package com.example.springbootmybatistest.dao;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.ID
     *
     * @mbggenerated
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    private Short userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private Short roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_ROLE.IS_DEL
     *
     * @mbggenerated
     */
    private String isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated
     */
    public UserRole(Short id, Short userId, Short roleId, String isDel) {
        this.id = id;
        this.userId = userId;
        this.roleId = roleId;
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_USER_ROLE
     *
     * @mbggenerated
     */
    public UserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.ID
     *
     * @return the value of T_USER_ROLE.ID
     *
     * @mbggenerated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.ID
     *
     * @param id the value for T_USER_ROLE.ID
     *
     * @mbggenerated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.USER_ID
     *
     * @return the value of T_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public Short getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.USER_ID
     *
     * @param userId the value for T_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Short userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.ROLE_ID
     *
     * @return the value of T_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public Short getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for T_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_ROLE.IS_DEL
     *
     * @return the value of T_USER_ROLE.IS_DEL
     *
     * @mbggenerated
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_ROLE.IS_DEL
     *
     * @param isDel the value for T_USER_ROLE.IS_DEL
     *
     * @mbggenerated
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }
}