package com.example.springbootmybatistest.mapper;

import com.example.springbootmybatistest.dao.RoleInfo;
import java.util.List;

public interface RoleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_INFO
     *
     * @mbggenerated
     */
    int insert(RoleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_INFO
     *
     * @mbggenerated
     */
    RoleInfo selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_INFO
     *
     * @mbggenerated
     */
    List<RoleInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleInfo record);
}